version: '3.8'

services:
  # Database
  database:
    build:
      context: ./database
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Backend
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  # Frontend Admin
  frontend-admin:
    build:
      context: ./frontend-admin
    ports:
      - "8080:80"

  # Frontend Public
  frontend-public:
    build:
      context: ./frontend-public
    ports:
      - "8081:80"

  # Web Server (Nginx)
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend-admin
      - frontend-public

volumes:
  db_data:
