services:
  # Database
  database:
    build:
      context: ./database
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Backend
  backend:
    build:
      context: ./backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - AI_SOURCE=${AI_SOURCE}
      - AI_MAX_DOCUMENTS=${AI_MAX_DOCUMENTS}
      - AI_URL=${AI_URL}
      - AI_MODEL=${AI_MODEL}
      - AI_TIMEOUT=${AI_TIMEOUT}
      - GEMINI_MODEL=${GEMINI_MODEL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped

  # Frontend Admin
  frontend-admin:
    build:
      context: ./frontend-admin
      args:
        VITE_API_BASE_URL: "/api/v1"
        VITE_API_BASE_LOGIN_URL: "/api"
    ports:
      - "9080:80"
    restart: unless-stopped

  # Frontend Public
  frontend-public:
    build:
      context: ./frontend-public
      args:
        VITE_API_BASE_URL: "/api/v1"
    ports:
      - "9081:80"
    restart: unless-stopped

  ollama :
    image : ollama/ollama:latest
    container_name : ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    volumes :
      - ollama_models:/root/.ollama
    ports :
      - "11434:11434"
    restart : unless-stopped
    # Use default entrypoint which runs 'ollama serve'

  # Web Server (Nginx)
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_started
      frontend-admin:
        condition: service_started
      frontend-public:
        condition: service_started
    restart: unless-stopped


volumes:
  db_data:
  ollama_models :
    name: ollama_models
